# ID of the project to link to in your Unweave account. All commands you run in this
# directory will be run against this project.
project_uri = "{{.ProjectURI}}"

# The default provider to use. You can override this with runtime flags
default_provider = 'unweave'

# Configure preferences for the Unweave providers you have configured with your project.
# Currently supported providers: `unweave`, `lambdalabs`, `aws`
[provider.unweave]

{{- range .Providers}}

[provider.{{.Name}}]
{{- end }}

# Configure resources for execs. 
# Example config:
# [[specs]]
# name   = "my-spec"
# [specs.cpu]
# type   = "x86_64" # only x86_64 is supported
# count  = 2
# memory = 4
# [specs.gpu]
# type   = "..." # see unweave ls-gpu-types <provider>
# count  = 1
# memory = 8
# [specs.hdd]
# size   = 10
# 
# This is the minimal required config:
[[specs]]
name = "default"
[specs.cpu]
type = "x86_64"

[sessions]
scp = false
sync = false
editor = "vscode"
